# 全体の設定
site_name: SextiarySector4
site_author: 'シフト02'
language: ja

repo_url: https://github.com/shift02/SextiarySector4
repo_name: SextiarySector4
edit_uri: ''

theme:
  name: 'material'
  language: ja
  features:
    - navigation.tabs
    - toc.integrate
  logo: img/orichalcum_gear_logo.png
  favicon: img/orichalcum_gear_logo.png


extra:
  generator: false


docs_dir: 'raw-docs'
site_dir: 'docs'

extra_css:
  - stylesheets/home.css

copyright: 'Copyright (c) shift02 2022'

# Navigation
nav:
  - ホーム: index.md
  - 要素一覧:
    - 概要: catalog/index.md
    - コア:
      - 概要: catalog/core/index.md
      - 葉っぱ: catalog/core/leaf.md
      - 葉っぱブロック: catalog/core/leaf_block.md
      - 葉っぱベッド: catalog/core/leaf_bed.md
      - プラスチックの盾: catalog/core/plastic_shield.md
    - 林業:
      - 概要: catalog/forestry/index.md
      - 樹液入りボトル: catalog/forestry/sap_bottle.md
  - ダウンロード: download.md
  - 更新履歴:
    - 一覧: changelog/index.md
    - 0.0.1: changelog/0.0.1.md
    - 0.0.2: changelog/0.0.2.md


# 拡張機能
markdown_extensions:
  - admonition
